---
- name: Install ansible-role-elastic
  hosts: conatel #"{{ target }}"
  become: true
  gather_facts: false
  tasks:
    - name: Install ansible-role-elastic
      include_role:
        name: '{{ item }}'
      with_items:
        - ansible-role-elastic

# - name: Install ansible-role-elastic
#   hosts: controlador #"{{ target }}"
#   become: true
#   gather_facts: false
#   tasks:
#     - import_role:
#         name: ansible-role-elastic
#         tasks_from: addnode 
